{
    'name': 'SIGMA HRMS Core',
    'version': '1.0',
    'summary': """Open HRMS Suit: It brings all Open HRMS modules""",
    'description': 'Main module of Open HRMS. It brings all others into a single module',
    'category': 'Generic Modules/Human Resources',
    'author': 'Indglobal digital',
    'company': 'Indglobal digital pvt ltd',
    'website': "https://indglobal.in/",
    'depends': [
                'hr_payroll_account',
                'hr_employee_updation',
                'hr_attendance',
                'hr_holidays',
                'hr_payroll',
                'hr_leave_request_aliasing',
                'hr_timesheet',
                'employee_creation_from_user',
                'hr_reminder',
                'backend_theme_v12',
                'odoo_web_login',
                'web_responsive',
                'employee_master',
               ],
    'data': [
        'views/menu_arrangement_view.xml',
        'views/hr_config_view.xml',
	    'views/template_view.xml',
    ],

    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
